### ISSUE TITLE
Scatter shows error when connecting

### ISSUE THREAD

**Issue by dliuproduction** [dfuse-io/ice#2]
![Screen Shot 2020-06-11 at 4 01 03 PM](https://user-images.githubusercontent.com/9066053/84433783-db71d480-abfc-11ea-8727-fb9952beee5c.jpg)

**Comment by tehlowkeywiz** [comment]
Fixed: Scatter removed in https://github.com/dfuse-io/ice/commit/1d81394d16765f8c12ed2a50debe31cef63fbc69
